### ISSUE TITLE
Issue after composer update

### ISSUE THREAD

**Issue by dharen008** [kenepa/resource-lock#48]
Issue after composer update
i tried to install it again using

composer require kenepa/resource-lock

Then error shows after you fix the issue on this thread https://github.com/kenepa/resource-lock/issues/42

Errors on the screenshot

![image](https://github.com/kenepa/resource-lock/assets/109984612/5e2d5997-b07d-478d-8f41-0f23b0004a8d)

**Comment by Jehizkia** [comment]
Thanks for reporting, I'll check it out!

**Comment by dharen008** [comment]
Thank you

error shows after you fix the issue on this thread https://github.com/kenepa/resource-lock/issues/42

**Comment by Jehizkia** [comment]
I've pushed a potential fix. Could you please run the installation using the latest release?

**Comment by dharen008** [comment]
still the same
![image](https://github.com/kenepa/resource-lock/assets/109984612/1203191a-4065-49ad-b378-2b9c3105fe27)

**Comment by Jehizkia** [comment]
In case you have your config published can you change this to the following and run the install command:
```
   /*
    |--------------------------------------------------------------------------
    | Filament Resource
    |--------------------------------------------------------------------------
    |
    | The resource lock filament resource displays all the current locks in place.
    | You are able to replace the resource Lock with your own resource class.
    |
    */
    'resource' => [
        'class' => \Kenepa\ResourceLock\Resources\LockResource::class,
    ],
```

**Comment by dharen008** [comment]
that fix the issue! thank you for the help!

**Comment by Jehizkia** [comment]
Ah, great! I'm glad I could be of help.

This was a mistake on my part. Thank you for the quick responses.
